admin:
  port: 9990

routers:
- protocol: http
  dtab: /svc => /$/inet/127.1/9990;
  servers:
  - port: 4140
    ip: 0.0.0.0
  interpreter:
    kind: io.l5d.namerd.http
    experimental: true
    namespace: example
    dst: /$/inet/namerdlb/4180
  identifier:
    kind: io.l5d.methodAndHost
  dstPrefix: /http
