admin:
  ip: 0.0.0.0
  port: 9991
interfaces:
  - kind: io.l5d.httpController
    ip: 0.0.0.0
    port: 4180
namers:
  - kind: io.l5d.consul
    host: consul
    prefix: /consul
storage:
  kind: io.l5d.consul
  experimental: true
  host: consul
  # this is default path in Consul where
  # Dtab routing info will be looked up.
  pathPrefix: /namerd/dtabs